setup: Fix hdf5 dll search in mingw
This fixes the following error in mingw environment:
Loading library to get build settings and version: hdf5.dll
error: Unable to load dependency HDF5, make sure HDF5 is installed properly
error: Could not find module 'hdf5.dll' (or one of its dependencies).
Try using the full path with constructor syntax.

The error is fixed by checking if the python executable
is compiled in MSVC environment using sys.version. If not
then search for libhdf5-0.dll file which is the name of
hdf5 shared library in mingw environment.