TST: Fix skipping i686 datatypes with newer versions of numpy
Apparently newer versions of numpy (1.19.5 is the oldest I have tested)
no longer declare 'float128' and 'complex256' on 32-bit x86.  Instead,
they declare 'float96' and 'complex192'.  Rewrite the test for
unsupported types to account for the two new types, and handle missing
types gracefully.

This fixes the following test failure:

    E       AttributeError: module 'numpy' has no attribute 'float128'

plus, later on (again):

    E   TypeError: Illegal length 24 for complex dtype